// https://zh.chaturbate.com/apps/user_uploads/3/rubzombie/
// https://zh.chaturbate.com/apps/sourcecode/king-freeloader-block-module/?version=326286&slot=3

// https://ar.chaturbate.com/apps/user_uploads/3/rubzombie/
// https://ar.chaturbate.com/apps/sourcecode/king-freeloader-block-module/?version=&slot=3

// startof KFB module - not for re-compilation
(function(c){function p(a,d){d&&"string"===typeof d&&d.length?c.sendNotice(a,d,"#dc5500","#ffffff","bold"):c.sendNotice(a,"","#d5ebf8","#6900cc","bold")}function k(a){function d(a){a.test(e)&&(l=!0)}function k(a){e=e.replace(a,b.replace)}var e=a.m,n=escape(e),f=a.user,g,l,b;Object.keys(m).forEach(function(h){!m.hasOwnProperty(h)||f===c.room_slug||/^nf/i.test(h)&&(a.tipped_recently||a.in_fanclub||a.is_mod)||(b=m[h],g=b.hasOwnProperty("testers")?b.testers:b.filters,l=!1,g.forEach(d),l&&(c.log(["kfb(mod)",
h+" censored",f,n].join("::")),b.hasOwnProperty("replace")&&(g=b.hasOwnProperty("filters")?b.filters:g,g.forEach(k)),b.hasOwnProperty("responce")&&p(b.responce.replace(/%%USER%%/g,f),f),b.hasOwnProperty("tobc")&&p(b.tobc.replace(/%%USER%%/g,f),c.room_slug),b.hasOwnProperty("X-Spam")&&b["X-Spam"]&&(a["X-Spam"]=b["X-Spam"]),a.m=e.toLowerCase()))});return a}var m={nff:{label:"No Freeloader ass, boobs, cum, pussy, open, or show requests",filters:[/(^|\s)a+(s|z)(s|z)+($|\s)/gi,/(^|\s)b+(o|0)+b+(s|z)*($|\s)/gi,
/(^|\s)(c|k)+u+m+($|\s)/gi,/(^|\s)s+h+(o|0)+w*($|\s)/gi,/(^|\s)(o|0)+p+e+n+($|\s)/gi,/(^|\s)f+(e|o|0){2,}t+\s*j+(o|0)+b+/gi,/(^|\s)p+u+(s|z)+(e|i|y)*($|\s)/gi,/(^|\s)c+l+(i|1)+t+(oris|0ris|0r1s)?($|\s)/gi,/(^|\s)\(\s*(\.|o|0)\s*y\s*(\.|o|0)\s*\)($|\s)/gi],replace:" (blank) ",responce:"%%USER%%, you must tip me or start Group/Private, if you want to see my pussy, ass, boobs or cum.",tobc:"%%USER%% Request Blocked :)"},nfg:{label:"No Freeloader :emotes",filters:[/:/g],replace:":\u00ad",responce:"%%USER%%, you must tip me or start Group/Private, if you want to use emotes.",
testers:[/(?:^|\s):([\w\-][\w\-]+)(?=\s|$)/g],tobc:"%%USER%% Emote Blocked :)"},nfcl:{label:"No Freeloader CAPS LOCK",responce:"%%USER%%, you must tip me or start Group/Private, if you want to use Caps Lock.",testers:[/[A-Z][A-Z]+/g],tobc:"%%USER%% Caps Blocked :)"},nfpm:{label:"No Freeloader PM requests",filters:[/(^|\s)pm($|\s)/g],replace:" (blank) ",responce:"%%USER%%, you must tip me or start Group/Private, if you want to PM.",tobc:"%%USER%% PM Blocked :)"},allc2c:{label:"No Cam2Cam requests, unless in Group/Private (to all)",
replace:" (blank) ",responce:"%%USER%%, you must start Group/Private, if you want to Cam2Cam.",testers:[/[ck]+a+m+\s*2+\s*(c|k)+a+m+/gi,/[ck]+a+m+\s*t(o|0)+\s*(c|k)+a+m+/gi,/[ck]+\s*2+\s*[ck]+/gi,/m+y+\s+(c|k)+a+m+/gi,/m+y+\s+r+(o|0)+m+/gi,/m+y+\s+p+r+(o|0)+f+i+[l1]+e*/gi,/[cs]+e+\s+m+[ey]/gi],tobc:"%%USER%% C2C Blocked :)","X-Spam":!0}};c.log("kfb(mod)::'king Freeloader Block (module)::rubzombie::2016.10.01_004::Freeloader-censoring auto-mod bot module.");var n=c.onMessage;c.onMessage=function(a){if("function"!==
typeof a)throw new TypeError(a+" is not a function");n(function(c){return a(k(c))});return a};c.onMessage(function(a){return a})})(cb);
// endof KFB module - not for re-compilation
