// https://chaturbate.com/apps/user_uploads/3/rubzombie/
// https://chaturbate.com/apps/sourcecode/no-grey-spammers/?version=&slot=3

// startof CBSv2 module - not for re-compilation
(function(a,k){function g(a){this.message=a}g.prototype=Error();g.prototype.name="InvalidCharacterError";a.btoa||(a.btoa=function(a){a=String(a);for(var f,b,n=0,c=k,q="";a.charAt(n|0)||(c="=",n%1);q+=c.charAt(63&f>>8-n%1*8)){b=a.charCodeAt(n+=.75);if(255<b)throw new g('"btoa" failed: The string to be encoded contains characters outside of the Latin1 range.');f=f<<8|b}return q});a.atob||(a.atob=function(a){a=String(a).replace(/=+$/,"");if(1==a.length%4)throw new g('"atob" failed: The string to be decoded is not correctly encoded.');
for(var f=0,b,n,c=0,q="";n=a.charAt(c++);~n&&(b=f%4?64*b+n:n,f++%4)?q+=String.fromCharCode(255&b>>(-2*f&6)):0)n=k.indexOf(n);return q})})("undefined"===typeof exports?this:exports,"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=");
(function(a){var k=cb.onMessage,g=null,u=null,f,b="#"+(cb.settings.hasOwnProperty("slot")?cb.settings.slot:"")+"CBSv2",n=/^\/#[0-3]CBSv2\//;cb.log("CBS::v2::CB app/bot data Save/restore::20170923.009::Release");cb.onMessage=function(c){if("function"!==typeof c)throw new TypeError(c+" is not a function");k(function(k){var d=k.m.replace(/\s*/g,"").split("/");if(3<d.length&&""===d[0]&&d[1]===b){if(g&&u&&k.user===cb.room_slug){var p=d[2];if(4===d.length)d[3]="?",k.m=d.join("/");else if(6===d.length){if(!(f||
{}).hasOwnProperty(p)){var q=g();f={};f[p]=a.btoa(a.unescape(a.encodeURIComponent(q)));q||cb.log("onSave returned no data.")}f.hasOwnProperty(p)&&(q=parseInt(d[3],10),p=f[p].slice(q,q+512),d[4]=p,d[5]=p.length,k.m=d.join("/"))}else 7===d.length&&("0"===d[3]&&(f={},f[p]=""),f.hasOwnProperty(p)&&(d[3]=f[p].length,d[6]=d[4].length,k.m=d.join("/"),d[4]?f[p]+=d[4]:(q=a.decodeURIComponent(a.escape(a.atob(f[p]))),u(q),cb.chatNotice("Previously Saved Data Restored.",cb.room_slug))))}k["X-Spam"]=!0}else n.test(k.m)&&
(k["X-Spam"]=!0);return c(k)});return c};cb.onRestore=function(a){if("function"!==typeof a)throw new TypeError(a+" is not a function");return u=a};cb.onSave=function(a){if("function"!==typeof a)throw new TypeError(a+" is not a function");return g=a};cb.onMessage(function(a){return a})})("undefined"===typeof exports?this:exports);
// endof CBSv2 module - not for re-compilation
var g=function(){function c(a){function e(){var a=/(..)(:..)(:..)/.exec(new Date),c=a[1]%12||12;return(10>c?"0"+c:c)+a[2]+a[3]+" "+(12>a[1]?"A":"P")+"M : "}a&&"string"===typeof a&&(c.hasOwnProperty("log")||(c.log=[]),c.log.push(e()+a),25<c.log.length&&c.log.shift(),a=("No Grey Spammers: "+a).replace(/\+/g,"\uff0b").replace(/&/g,encodeURIComponent("&")));c.hasOwnProperty("log")||cb.log(a.replace(/(\r\n|\n|\r|\\n)/gm," ").trim())}function D(a){var c=Array.prototype.slice.call(arguments),e=0,f;if(a&&
"string"===typeof a){if("Enable"===cb.settings.multi_line_safe){var l=a.split(/ *\n */);e=l.length;a=l[0]}c[0]=("No Grey Spammers: "+a.replace(/\+/g,"\uff0b")).replace(/&/g,encodeURIComponent("&"))}cb.chatNotice.apply(cb,c);for(f=1;f<e;f++)c[0]=l[f].replace(/\+/g,"\uff0b").replace(/&/g,encodeURIComponent("&")),cb.chatNotice.apply(cb,c)}function E(a,c){var e=Array.prototype.slice.call(arguments);c&&"string"===typeof c&&c.length&&(e[0]=""+a,D.apply(F,e))}function H(a){function x(a){switch(a){case q.h:return"None (no spam blocking)";
case q.f:return"Basic (block messages that include known spam phrases)";case q.g:return"Enhanced (block messages that include known spam phrases or non-english characters)";case q.b:return"Advanced (block messages that include known spam phrases, non-english characters or excessive (character/word) repetition)"}}function D(a){if(2<l[a]){k+="\u00a0\u00a0"+a+":\n";var b=0;for(p=t.length;b<p;b++)0===t[b].indexOf(a+": ")&&(k+="\u00a0\u00a0\u00a0\u00a0"+t[b].substr(a.length+2)+"\n")}}function F(a){var b=
!1;n.hasOwnProperty("auto_user")&&n.hasOwnProperty("auto_time")&&(b=1500>B-n.auto_time&&n.auto_user===a);n.auto_user=a;n.auto_time=B;return b}function K(a,b){var c=!1;b=b.replace(/_[0-9a-f]+/ig,"");n.hasOwnProperty("echo_user")&&n.hasOwnProperty("echo_text")&&(c=n.echo_text===a&&n.echo_user===b);n.echo_user=b;n.echo_text=a;return c}var n=H,B=(new Date).valueOf(),m=a.m,u=m.replace(/[\W_]/g,"").toLowerCase(),I=u.replace(/[aeiou]/g,""),h=a.user,b="rubzombie"===h,v=h===cb.room_slug,y=a.is_mod,J=a.in_fanclub,
z=a.has_tokens||a.tipped_recently||a.tipped_alot_recently||a.tipped_tons_recently,L=a.hasOwnProperty("is_pm")&&a.is_pm,r=J?cb.settings.fans:y?cb.settings.mods:a.has_tokens?cb.settings.blus:cb.settings.grys,M=/\/(ngs|nogreyspammers|#[0-3])?(help|spam|\?)/ig,w,p,d=!1;v&&a.gender&&(n.gender=a.gender);!v||b&&"rubzombie"===cb.room_slug||(r=q.h);if(!a["X-Spam"]&&"/"===m.trim()[0])for(;null!==(w=M.exec(m));){var A=(w[1]||"ngs").toLowerCase();if("ngs"===A||"nogreyspammers"===A||A===G){var k="";a["X-Spam"]=
!0;A=w[2].toLowerCase();switch(A){case "?":case "help":b&&(k+="version: 2018.05.10_0\n*\ud83c\udd78\ud83c\udd7d\ud83c\udd82\ud83c\udd83\ud83c\udd70 \ud83c\udd71\ud83c\udd70\ud83c\udd7d able* For maximum protection against chat spam, set all blockers to Advanced.\nNo Grey Spammers: ");k+="Currently: "+(J?"Fan":y?"Mod":a.has_tokens?"Blue":"Grey")+".\nNo Grey Spammers: Settings:\n";k=v||y?k+("\u00a0\u00a0Fans: "+x(cb.settings.fans)+",\n\u00a0\u00a0Mods: "+x(cb.settings.mods)+",\n\u00a0\u00a0Blues: "+
x(cb.settings.blus)+",\n\u00a0\u00a0Greys: "+x(cb.settings.grys)+",\n"):k+("\u00a0\u00a0You: "+(l.hasOwnProperty(h)&&2<l[h]?"(Silenced)":x(r))+",\n");k+="\nNo Grey Spammers: In-chat commands:\n\u00a0\u00a0/?\n\u00a0\u00a0/help - show this message";if(v||y)k+="\n\u00a0\u00a0/spam - list silenced spammers and their spam";v&&(k+="\nTo adjust settings, deactivate & re-launch "+(C?"app":"bot")+".");E(k,h,"#f2f9fd");c("Debug mode enabled. Type /debug again to disable.");break;case "spam":k="",v||y?(Object.keys(l).forEach(D),
k=k.length?"Silenced Spammers:\n"+k+"\nNo Grey Spammers: To un-silence all silenced spammers, deactivate & re-launch "+(C?"app":"bot")+".":t.length?"Silenced Spammers:\n\u00a0\u00a0(None)\nNo Grey Spammers: Spam Blocked messages:\n\u00a0\u00a0"+t.join("\n\u00a0\u00a0"):"No messages have been Spam Blocked, so far."):k="Sorry, the /"+("string"===typeof w[1]?w[1]:"")+w[2]+" command is only available to broadcasters and moderators.",E(k,h,"#f2f9fd")}}}if(l.hasOwnProperty(h)&&2<l[h])return a["X-Spam"]=
!0,e||(a.m="*** Sorry, you have been silenced for repeatedly spamming chat. ***",a.background="#595959",a.c="#999999"),c("onMessage: "+((new Date).valueOf()-B)+"ms"),a;if(!(a["Z-Instaban"]||a["Z-Spam-Filtered"]||a["X-Spam"]||L)&&r!==q.h){F(h)&&(d=!0,e||(a.m="*** Sorry, spam isn't allowed in chat. ***"),c("automated match"));!d&&/(open|record|see|tap|view).*(my).*(bio|cam)/i.test(h)&&(d=!0,e||(a.m="*** Sorry, spam isn't allowed in chat. ***"),c("username match"));!d&&/((\(\d{3}\) ?)|(\d{3}[\- ]?))?\d{3}[\- ]?\d{4}/i.test(m)&&
(d=!0,e||(a.m="*** Sorry, spam isn't allowed in chat. ***"),c("phone match"));!d&&/[\u2580-\u259F]/.test(m)&&(d=!0,e||(a.m="*** Sorry, spam isn't allowed in chat. ***"),a["Z-Instaban"]=!z,c("spacer match"));!d&&/[\xa0-\xff\u0100-\u017f\u0250-\u02ff\u0370-\u03ff\u0400-\u04ff\u1d00-\u1dff\u275f\ua720-\ua7ff]|\ud800[\udea0-\udede\udf00-\udf2e\udf30-\udf4e]|\ud802[\udd00-\udd1e]|\ud835[\udc00-\udffe]|\ud83c[\udd00-\uddfe]/.test(m)&&(d=!0,e||(a.m="*** Sorry, spam isn't allowed in chat. ***"),a["Z-Instaban"]=
!z,c("fancy text char analog match"));!d&&K(m,h)&&(d=!0,e||(a.m="*** Sorry, spam isn't allowed in chat. ***"),c("echo match"));b=0;for(p=f.i.length;!d&&b<p&&!(I.length<f.i[b].length);b++)!0===(d=-1!==I.indexOf(f.i[b]))&&(e||(a.m="*** Sorry, spam isn't allowed in chat. ***"),c("simple match ("+b+"): "+f.i[b]));if(n.gender&&"c"!==n.gender)for(b=0,p=f.s.length;!d&&b<p;b++)!0===(d=f.s[b].test(m))&&(e||(a.m="*** Sorry, spam isn't allowed in chat. ***"),a["Z-Instaban"]=!z,c("singleton match ("+b+"): "+
f.s[b].source));b=0;for(p=f.text.length;!d&&b<p;b++)!0===(d=f.text[b].test(m))&&(e||(a.m="*** Sorry, spam isn't allowed in chat. ***"),~[1,9,10,15,16,17,19,28,29].indexOf(b)&&(a["Z-Instaban"]=!z),c("text match ("+b+"): "+f.text[b].source));b=0;for(p=f.o.length;!d&&b<p;b++)!0===(d=f.o[b].test(u))&&(e||(a.m="*** Sorry, spam isn't allowed in chat. ***"),c("plain match ("+b+"): "+f.o[b].source));b=0;for(p=f.j.length;!d&&b<p;b++)!0===(d=(new RegExp("(?:^|\\s):"+f.j[b]+"(?=\\s|$)","")).test(m))&&(e||(a.m=
"*** Sorry, spam isn't allowed in chat. ***"),c("blacklist emoticons match ("+b+"): "+f.j[b]));b=0;for(p=f.l.length;!d&&b<p;b++)!0===(d=(new RegExp("(?:^|\\s):"+f.l[b]+"(?=\\s|$)","")).test(m))&&(e||(a.hasOwnProperty("m-raw")||(a["m-raw"]=a.m),a.m="*** Sorry, spam isn't allowed in chat. ***"),a["Z-Instaban"]=!z,c("IsPleaseYourProstateDotComDown emoticons match ("+b+"): "+f.l[b]));!d&&/(?:^):([A-Z][\w\-]+\d\d)(?=$)/.test(m)&&(d=!0,e||(a.hasOwnProperty("m-raw")||(a["m-raw"]=a.m),a.m="*** Sorry, spam isn't allowed in chat. ***"),
c("suspected IsPleaseYourProstateDotComDown emoticon match: "+RegExp.$1));d||r!==q.g&&r!==q.b||!/[^\u0000-\u0080\u00ad\u00b4\u2605\u2606\u2654\u2655\u265a\u265b]/.test(m)||(d=!0,e||(a.m="*** Sorry, non-english characters aren't allowed in chat. ***"));d||r!==q.b||(u=m.toLowerCase().split(/\W+/),u.length&&!0===(d=.28>u.filter(function(a,b,c){return c.indexOf(a)===b}).length/u.length)&&(e||(a.m="*** Sorry, excessive word repetition isn't allowed in chat. ***"),c("too many repeated words")));!d&&r===
q.b&&/(\D|\D\D|\D\D\D)\1{3,}/.test(m.toLowerCase())&&(d=!0,e||(a.m="*** Sorry, excessive character repetition isn't allowed in chat. ***"),c("too many repeated chars"));d&&(a["X-Spam"]=!0,l.hasOwnProperty(h)?l[h]++:l[h]=1,e||(a.m+=" <<< spHammer hit#"+l[h],a.background="#595959",a.c="#999999"),t.push(h+": "+m));d&&2<l[h]&&E("user "+h+" has spammed your chat "+l[h]+" times and has been silenced!\nNo Grey Spammers: Type /spam for a list of all silenced spammers and their spam or /help for help.\nNo Grey Spammers: To un-silence all silenced spammers, deactivate & re-launch "+
(C?"app":"bot")+".",cb.room_slug,"#f37e7e");a["Z-Instaban"]&&cb.sendNotice("\ud83c\udd78\ud83c\udd7d\ud83c\udd82\ud83c\udd83\ud83c\udd70 \ud83c\udd71\ud83c\udd70\ud83c\udd7d "+h,cb.room_slug)}c("onMessage: "+((new Date).valueOf()-B)+"ms");return a}var f={s:[/(\b|\xB0)(((bo|gu)y[sz]|jungen)[\.!]*)\s*$/i],text:[/^(<[<-]*)?\s*[\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u206F\u3000\uFEFF]+/,/^(<[<-]*)?\s*([\u0370-\u03FF\u0400-\u04FF\u2580-\u259F\u3000-\u303F\uFF00-\uFFEF]|[\uD800-\uDB7F][\uDC00-\uDFFF])+(?![\u0370-\u03FF\u0400-\u04FF\u2580-\u259F\u3000-\u303F\uFF00-\uFFEF]|[\uD800-\uDB7F][\uDC00-\uDFFF]|$)/,
new RegExp("^\\s*"+cb.room_slug,"i"),/\{"m":"/,/\b([ck][eil13]*c*k|[i1]n+f+[o0]|j[io01]+n|k[o0]+n+t+[a4]+k+t+[ei13]+r+t|l[o0]+k|[o0]n|[o0]p+[e3]+n|pl+[ae34]*[sz]+[e3]?|r[ae34]+d|sc+h+[au4]+t|s[e3]+|t[a4]+p|v[eiu13]+w?|v[i1]*s+[i1]*t|w[a4]+t+c+h).*\b(my|m[e3]+[i1]+n|m[i1]+c+h).*\b(bi+[o0]|c[a4]+m|n[a4]+m+[e3]?|p[a4]+g+[e3]?|pr+[o0]*f+[il1]+[e3]?|[r[o0]+m|wi?s+h+l+i?s+t)/i,/(\$+.*(offer|pm|proposal)|(offer|pm|proposal).*\$+)/i,/(\$\d+.*(meet)|(meet).*\$\d+)/i,/k(\.i\.|!)k\s+me:/i,/(?:\b|_)(?:like|want).*(?:\b|_)to(?:\b|_).*(?:\b|_)(c|cam|c4m)([2\u2777\u2781\u278B\uFF12]|\uD835[\uDFD0\uDFDA\uDFE4\uDFEE\uDFF8])\1/i,
/(?:\b|_)(c|cam|c4m)\s*([2\u2777\u2781\u278B\uFF12]|\uD835[\uDFD0\uDFDA\uDFE4\uDFEE\uDFF8])\s*\1(?:\b|_).*\??/i,/(\uD800\uDF02|\uD835\uDDD6|\uD835\uDCD2|\uD83C\uDD72|\uFF23).*([2\u2777\u2781\u278B\uFF12]|\uD835[\uDFD0\uDFDA\uDFE4\uDFEE\uDFF8]).*\1/,/.+[!\-]\s+\d\d$/,/(<[<-]+|\b(bb's|ease|hot\s+free)\b)/i,/([?)\\\xA1])\1+\s*$/i,/(\b|\xB0)(check|c-ute|(for|my)[\.!]|i\s*wan(na|t)|\/)\s*$/i,/^(<?\s*(:([\w-]{1,})\s+)?(a\s*(boy|guy|junge?|man)|bio|boys|cam|guys|page|room)\s*|(<\s*|:([\w-]{1,})\s+)+(me)\s*)$/i,
/^<?\s*(:([\w-]{1,})\s+)?(check\s*(out)?|f.ck|get|i\s*want|look(ing)?|see|sex|view|visit|watch)\s*(at|for|my|out|with)?\s*$/i,/^<?\s*(:([\w-]{1,})\s+)?((fuck|sex)\s*with\s*)?((crazy|horny|hot|naughty|sexy|stunning)?\s*(dame|frau|lady|me|milf|woman)\s*(\.|boys|guys)|meet|searching|see(king)?|watch)\s*$/i,/\b(check|look)\s*(at|out)\s*(me|my)\b/i,/(?:^|\s):check\S*bio/i,/(w\s*h\s*o|m\s*a\s*y\s*b\s*e).+(\?|!)(\s):([\w-]{1,})(?=$)/i,/[\uFF21-\uFF5A]/,/\b(WWW|COM|NET|INFO|ORG|BIZ)\b/,/[\W_]c[o0]m([\W_]|$)/i,
/(^|[\W_])www[\W_]{1,3}[a-z0-9][a-z0-9\-]*[a-z0-9][\W_]{1,3}[a-z]{2,4}([\W_]|$)/i,/w([\W_])w\1w|c([\W_])o\2m([\W_]|$)/i,/([\W_]at|@)[\W_]{0,3}[a-z0-9][a-z0-9\-]*[a-z0-9][\W_]{1,3}\b(net|biz|info|org)\b/i,/(_|([A-Z_])\2+)(bio|cam|com|c2c|free|girls|me|my|online|open|privates|record|see|tap|to?ke?ns?|view|www)\1/,/i *am *online|(check|come( *to)?|watch) *my *(room|.*channel)|(f.?ck|s?ex).*\s:[\w-]*(cash|money)|willst *du/i,/sex\s+in\s+your.+\-\->.+\.me/i],o:[/(arentaloud|camison|camonthisroom|cumwatchme|datefuckeu|erotimonet|goddamb|gru?vt?e?ochat|^(maybe|who)(fu?ck|s?ex)(me)?|lookmeup|nudesypl|wat?ch(menut|(my)?cam)|xxxdatepl)/,
/(hermosacara|holasoynuevaonlineahora|junge?s?|mast(ru|ur)beren|meencanta|mipeneay|mitmir|polla|quieres.*follada|quierofollarte|wollen(ficken|sex))/,/(camportal|camsex|deutsche|junges).*readbio/,/free.*che?c?k.*tinyurl.*(dot|d0t)?.*(www|com|net|biz|info|org).*camtokens/,/che?c?k.*(at)?.*(dot|d0t)?.*(www|com(?!e)|net|biz|info|org)/,/CamSessions.*(at)?.*(dot|d0t)?.*(www|com|net|biz|info|org)/,/(ch[a4]t|pm|m[e3]*[s5]+[a4]*g).*me.*id.*on.*profile?/,/(b[e3]such[e3]|[ck][eil13]*c*k|g[o0]t[o0]|[i1]nf[o0]|j[io01]+n|k[o0]nt[a4]kt[ei13]+rt|l[o0]+k|[o0]p[e3]n|pl[ae34]*[sz][e3]?|r[ae34]+d+[^y]|sch[au4]+t|s[e3]+|t[a4]p|v([ei13]+w|u+)|v[i1]*s[i1]*t|w[a4]tch).*(my|[^io]m[ei13]+n?|m[i1]+ch).*(bi[o0]|c[a4]m|n[a4]m[e3]?|p[a4]g[e3]?|pr[o0]*f[il1]+[e3]?|[^f]r[o0]+m|s[e3]?[i1]t[e3]|tr[a4]nsm[il1]t|wi?shli?st)/,
/(b[e3]such[e3]|[ck][eil13]*c*k|g[o0]t[o0]|[i1]nf[o0]|j[io01]+n|k[o0]nt[a4]kt[ei13]+rt|l[o0]+k|[o0]p[e3]n|pl[ae34]*[sz][e3]?|r[ae34]+d|sch[au4]+t|s[e3]+|t[a4]p|v([ei13]+w|u+)|v[i1]*s[i1]*t|w[a4]tch).*(my|m[i1]+ch).*(bi[o0]|c[a4]m|n[a4]m[e3]?|[o0]ut|p[a4]g[e3]?|pr[o0]*f[il1]+[e3]?|[^f]r[o0]+m|s[e3]?[i1]t[e3]|tr[a4]nsm[il1]t|wi?shli?st)/,/[o0]kcup[i1]d/,/new.*look.*my.*(video|cam)/,/(seksanon).*(dot|d0t)?.*pl/,/(addme).*(at)?live.*nl/,/(srbije|crnrgore|bosne|hrvatske).+(srbije|crnrgore|bosne|hrvatske)/,
/new.*girl.*come.*see/,/phone.*sex.*we.*watch/,/pm.*for.*private.*show/,/on.*cam.*take.*look/,/callme.*\d{3}.*\d{3}.*\d{4}/,/(^|[^l])come.*see.*(me|my)(\s|$)/,/big.*dick.*on.*cam/,/tipped.*\d+.*token/,/(click|get.*tk|go).*[io]n.*my.*(bio|page|room)/,/(aufpimmel|deutschehier|deutschekerle|esseinhatwer|ficktmich|fotzeoder|insarschloch|meinefotze|meinemuschi|meinetitten|mirkerle|mitmirgratis|scheissegeil|werbockaufn)/],i:"dlnws gtmyb mcmcm pnmnw sxlfm chnskv cht4fr ctylvm fllwmt frtkns pnmycm wgwgwg wnphn7 bst4cms cmnmyrm httpggl kkcmscm lnknmyb lv4prty lvtrffn nd4strp prfllsn bnjknntt kkmlvlns nsxyjngs pssy4shw sckmydck sxnyrcty sxnyrtwn vcmsssns wlchstdt 100kstnls chnnmnwhr cmsssnscm frrgstrtn grls4prty hlpmcmncm llgcmdtcm prmmchtcm rcrdsfrfr rgclsngsn sndtdrtch tknsgnrtr tmrqrllh1 tpgmscrck bfrtsptchd cbprvtsc0m chtrclbc0m fndgrlfrsx glsmtrprtl mnhndynmmr pttldyffrs schnmnprfl schtglbntr snddrtchlv wwwsxchtsr chtrtknsc0m knntjmlgckn lslsnndmldn stdchlngwlg strmngnkdcm wtchmcmgrls bwhlspplslst chbnnjngsgls dtschmtrprtl fndfrtknshck hrgldtschkrl pyplrwstrnnn schfdsmwgdch wsnddglnpmml wstrnnnrpypl jckjxshrngnds jngnschnmnknt kstnlsndhnrsk llrdngsnchthr mncmstjtztchn mnschwnzstnln rcrdngwbcmc0m wndmrmnfrrlds cmtmmvryhrnynw dknnmnglbwchsn hssmlfwllsxhbn mprdndstrngtrk n1gnhmpgstfrtg nlywmnrcplskyp ynggrlnfrntfcm chtwththswsmgrl stdnglchnnmnwhr wnnjrktwthmfrfr fsllnghtpcsndvds wnnchtwthyllfrfr dsthtdstwchmmrsnd hbknfnnzllnntrssn nrnchbzckmtdntpps schfcktrffnndcmsx fdrstdnglchnnmnwhr llnfssthnmprflvnmr nynwnnjrktwthmfrfr vrllmsndfstnrdtsch glbdgbtsgrnchtmhrdr myslbrngstrstnglcys snddwskstnlsndglrst wsnddnnnndglndtschn chtrbtknnmndchvrgssn ftzstmgglndbrchtshrt mchvrdrcmllswshrwllt nynhrdrmstfckldrmlfs chtrbttknsddrblgsptcm mchnchtlngwrtnndkmmzmr wrbckhtknnmchdjmlbschn kstnlsdtngprtlndtschlnd ntrssntbrmchfndstdnmnmprfl wnnjschtnmnprflndkntktrtmchdrt hbthrgntlchdhlfschlgschffthrvlldtn thsmnstrlysnfbtchsllngthmtfhsgrlfrnd dspmmrsndnfchzdmmvnjdmmdwrdnsgbnntndnsnstnflltdchknrfsnbldsnngwrbngrn".split(" "),
l:"JohnnyPott18 JumbledOne90 LoboDefense14 Loovian MeMoosta59 Michaelanthony32112346 Mishmoo44 MonnehMaker61 NeonDisease60 OldSkcool OldWarrior62 PartiallyWindow55 Pascalwb PastelFlamingo15098 PATthePOWER Pdilla12 PureReason2 Rassilon388 RayRoyStrickland63 RobertsFamily32 SagaNye Sarahc9581 StalinWasAJerk33 Stubby949 Synikul93 Terazilla28 ThatSpanishLover TheHandyman147 Thisishelpful Tom944495 TooMuchToDoo58 TwisterSF32 Tykozy82 UncleRichardson13 UpvotesLarryDavid27 ViStands4 Whoopwhoop779 Xanola ZeroFucksGiven0015".split(" "),
j:"anarchy dance69 endlesspoop exbf extremevomit extremevomit2 extremevomitscat FISTING fuckass1 gape420 gay gay6 gaybj gayfuck2 gayfuck5 gaysuck2 goats3 gross kena kisshug55 kisshug56 kisshug57 modme moderator04210 pm2 pooprow2 powerbottom prolapse56 prolapse57 prolapse58 shit50 shit55 shithead takeit tubgirl3 vbutt wag".split(" ")},q={h:"None",f:"Basic",g:"Enhanced",b:"Advanced"},F=this,G=null,C,t=[],l={},e=!0;return{a:q,u:function(){cb.settings.hasOwnProperty("slot")&&(G="#"+cb.settings.slot);
C="#0"===G;e="Yes"===cb.settings.silent_mode},onMessage:H}}();
cb.settings_choices=[{choice1:g.a.h,choice2:g.a.f,choice3:g.a.g,choice4:g.a.b,defaultValue:g.a.f,label:"Fans (Fan Club Members) spam blocker",name:"fans",required:!0,type:"choice"},{choice1:g.a.h,choice2:g.a.f,choice3:g.a.g,choice4:g.a.b,defaultValue:g.a.f,label:"Mods (Moderator) spam blocker",name:"mods",required:!0,type:"choice"},{choice1:g.a.h,choice2:g.a.f,choice3:g.a.g,choice4:g.a.b,defaultValue:g.a.g,label:"Blues (Members with Tokens) spam blocker",name:"blus",required:!0,type:"choice"},{choice1:g.a.h,
choice2:g.a.f,choice3:g.a.g,choice4:g.a.b,defaultValue:g.a.b,label:"Greys (Everyone Else) spam blocker",name:"grys",required:!0,type:"choice"},{choice1:"Yes",choice2:"No",defaultValue:"Yes",label:"Block Spam Silently (spammers won't known their messages are being blocked)",name:"silent_mode",required:!1,type:"choice"},{choice1:"Enable",choice2:"Disable",defaultValue:"Disable",label:"(Multi-line Safe Mode)",name:"multi_line_safe",type:"choice"}];cb.onMessage(function(c){return g.onMessage(c)});g.u();
