// https://en.chaturbate.com/apps/user_uploads/0/rubzombie/
// https://en.chaturbate.com/apps/sourcecode/tip-the-magic-number/?version=&slot=0

// startof CBSv2 module - not for re-compilation
(function(a,k){function g(a){this.message=a}g.prototype=Error();g.prototype.name="InvalidCharacterError";a.btoa||(a.btoa=function(a){a=String(a);for(var f,b,n=0,c=k,q="";a.charAt(n|0)||(c="=",n%1);q+=c.charAt(63&f>>8-n%1*8)){b=a.charCodeAt(n+=.75);if(255<b)throw new g('"btoa" failed: The string to be encoded contains characters outside of the Latin1 range.');f=f<<8|b}return q});a.atob||(a.atob=function(a){a=String(a).replace(/=+$/,"");if(1==a.length%4)throw new g('"atob" failed: The string to be decoded is not correctly encoded.');
for(var f=0,b,n,c=0,q="";n=a.charAt(c++);~n&&(b=f%4?64*b+n:n,f++%4)?q+=String.fromCharCode(255&b>>(-2*f&6)):0)n=k.indexOf(n);return q})})("undefined"===typeof exports?this:exports,"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=");
(function(a){var k=cb.onMessage,g=null,u=null,f,b="#"+(cb.settings.hasOwnProperty("slot")?cb.settings.slot:"")+"CBSv2",n=/^\/#[0-3]CBSv2\//;cb.log("CBS::v2::CB app/bot data Save/restore::20170923.009::Release");cb.onMessage=function(c){if("function"!==typeof c)throw new TypeError(c+" is not a function");k(function(k){var d=k.m.replace(/\s*/g,"").split("/");if(3<d.length&&""===d[0]&&d[1]===b){if(g&&u&&k.user===cb.room_slug){var p=d[2];if(4===d.length)d[3]="?",k.m=d.join("/");else if(6===d.length){if(!(f||
{}).hasOwnProperty(p)){var q=g();f={};f[p]=a.btoa(a.unescape(a.encodeURIComponent(q)));q||cb.log("onSave returned no data.")}f.hasOwnProperty(p)&&(q=parseInt(d[3],10),p=f[p].slice(q,q+512),d[4]=p,d[5]=p.length,k.m=d.join("/"))}else 7===d.length&&("0"===d[3]&&(f={},f[p]=""),f.hasOwnProperty(p)&&(d[3]=f[p].length,d[6]=d[4].length,k.m=d.join("/"),d[4]?f[p]+=d[4]:(q=a.decodeURIComponent(a.escape(a.atob(f[p]))),u(q),cb.chatNotice("Previously Saved Data Restored.",cb.room_slug))))}k["X-Spam"]=!0}else n.test(k.m)&&
(k["X-Spam"]=!0);return c(k)});return c};cb.onRestore=function(a){if("function"!==typeof a)throw new TypeError(a+" is not a function");return u=a};cb.onSave=function(a){if("function"!==typeof a)throw new TypeError(a+" is not a function");return g=a};cb.onMessage(function(a){return a})})("undefined"===typeof exports?this:exports);
// endof CBSv2 module - not for re-compilation
var c=0,d={},e=null,f=0,g=null,h=0,k=Math.floor(91*Math.random()),l=0,m=null,n={template:"3_rows_of_labels",row1_label:"Tokens Received:",row1_value:"...",row2_label:"Best Low Guess:",row2_value:"...",row3_label:"Best High Guess:",row3_value:"..."};function p(a){return!(""===a||void 0===a||null===a)}function q(){var a=cb.room_slug;return a?a+"'s":"the"}function r(a){return"#"+a.replace(/[^a-z0-9_]+/gi,"-")+" "}
function s(a,b){b&&"string"===typeof b&&b.length?cb.chatNotice("Magic #: "+a,b,"#dc5500","#ffffff","bold"):cb.log("Magic #: userNotice: missing user: "+a)}function t(a){var b;a=a||"??";return(b="number"===typeof b?b:12)&&a.length>b?a.substring(0,b-1)+"\u2026":a}
function u(){n.row1_value=l;c||(c=cb.settings.bias||10);var a="",b=h?h+1:c,v=f?f-1:c+100-10;m?"Winner:"!==n.row3_label&&(n.row2_label="Magic #:",n.row2_value=c+k,n.row3_label="Winner:",n.row3_value=m,a=["Game over!",m,"tipped",q(),r("Magic Number"),c+k,"and wins the",r(cb.settings.prize||""),"prize!"].filter(p).join(" ")):(h&&(a=h+" ("+t(g)+")",n.row2_value!==a&&(n.row2_value=a)),f&&(a=f+" ("+t(e)+")",n.row3_value!==a&&(n.row3_value=a)),a=["Tip",q(),r("Magic Number"),v-b?b+".."+v:"","and win the",
r(cb.settings.prize||""),"prize."].filter(p).join(" "));cb.drawPanel();u.hasOwnProperty("subject")||(cb.log("Magic #: originally by: remmbermytitans, re-boot by: rubzombie, version: 07/27/2014"),u.subject="",s("For Broadcaster-eyes Only: "+(c+k),cb.room_slug));a&&u.subject!==a&&(cb.changeRoomSubject(a),u.subject=a)}
cb.settings_choices=[{"default":"Private show",label:"Magic # Prize",maxLength:511,minLength:1,name:"prize",type:"str"},{defaultValue:10,label:"Magic # Minimum Tip",minValue:10,name:"bias",required:!1,type:"int"}];cb.onTip(function(a){var b=a.amount;a=a.from_user;l+=b;m?d.hasOwnProperty(a)||(s("Game over, man! Game over!",a),d[a]=!0):b<c+k?!h||b>h?(h=b,g=a):s("Higher ;)",a):b>c+k?!f||b<f?(f=b,e=a):s("Lower ;)",a):m=a;u()});cb.onDrawPanel(function(){return n});u();
