// https://fr.chaturbate.com/apps/user_uploads/2/nightseduce/
// https://fr.chaturbate.com/apps/sourcecode/nightseduce-soul-king/?version=&slot=2

// https://es.chaturbate.com/apps/user_uploads/3/nightseduce/
// https://es.chaturbate.com/apps/sourcecode/nightseduce-soul-king/?version=&slot=3

// startof CBSv2 module - not for re-compilation
(function(a,h){function f(a){this.message=a}f.prototype=Error();f.prototype.name="InvalidCharacterError";a.btoa||(a.btoa=function(a){a=String(a);for(var g,b,m=0,d=h,q="";a.charAt(m|0)||(d="=",m%1);q+=d.charAt(63&g>>8-m%1*8)){b=a.charCodeAt(m+=.75);if(255<b)throw new f('"btoa" failed: The string to be encoded contains characters outside of the Latin1 range.');g=g<<8|b}return q});a.atob||(a.atob=function(a){a=String(a).replace(/=+$/,"");if(1==a.length%4)throw new f('"atob" failed: The string to be decoded is not correctly encoded.');
for(var g=0,b,m,d=0,q="";m=a.charAt(d++);~m&&(b=g%4?64*b+m:m,g++%4)?q+=String.fromCharCode(255&b>>(-2*g&6)):0)m=h.indexOf(m);return q})})("undefined"===typeof exports?this:exports,"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=");
(function(a){var h=cb.onMessage,f=null,p=null,g,b="#"+(cb.settings.hasOwnProperty("slot")?cb.settings.slot:"")+"CBSv2",m=/^\/#[0-3]CBSv2\//;cb.onMessage=function(d){if("function"!==typeof d)throw new TypeError(d+" is not a function");h(function(h){var e=h.m.replace(/\s*/g,"").split("/"),k,r;3<e.length&&""===e[0]&&e[1]===b?(f&&p&&h.user===cb.room_slug&&(k=e[2],4===e.length?(e[3]="?",h.m=e.join("/")):6===e.length?((g||{}).hasOwnProperty(k)||(r=f(),g={},g[k]=a.btoa(a.unescape(a.encodeURIComponent(r))),
r||cb.log("onSave returned no data.")),g.hasOwnProperty(k)&&(r=parseInt(e[3],10),k=g[k].slice(r,r+512),e[4]=k,e[5]=k.length,h.m=e.join("/"))):7===e.length&&("0"===e[3]&&(g={},g[k]=""),g.hasOwnProperty(k)&&(e[3]=g[k].length,e[6]=e[4].length,h.m=e.join("/"),e[4]?g[k]+=e[4]:(r=a.decodeURIComponent(a.escape(a.atob(g[k]))),p(r),cb.sendNotice("Previously Saved Data Restored.",cb.room_slug))))),h["X-Spam"]=!0):m.test(h.m)&&(h["X-Spam"]=!0);return d(h)});return d};cb.onRestore=function(a){if("function"!==
typeof a)throw new TypeError(a+" is not a function");return p=a};cb.onSave=function(a){if("function"!==typeof a)throw new TypeError(a+" is not a function");return f=a};cb.onMessage(function(a){return a})})("undefined"===typeof exports?this:exports);
// endof CBSv2 module - not for re-compilation
function g(e,r,c,d){var k,a=arguments.length-4;if(1<a&&-1<Array.prototype.slice.call(arguments).indexOf(d,4))for(k=0;k<a;k++)this["choice"+(k+1)]=arguments[k+4];else for(a++,k=0;k<a;k++)this["choice"+(k+1)]=arguments[k+3];this.defaultValue=d;this.label=e;this.name=r;null===c||c||(this.required=!!c);this.type="choice"}
var y=function(e){var r=this,c=e.settings,d="",k=!1,a={i:!1,h:c.hasOwnProperty("slot")?"#"+c.slot:null,g:function(){return"#0"===a.h?"app":"bot"},b:function u(a){if(a&&"string"===typeof a){u.hasOwnProperty("log")||(u.log=[]);var f=/(..)(:..)(:..)/.exec(new Date),d=f[1]%12||12;u.log.push((10>d?"0"+d:d)+f[2]+f[3]+" "+(12>f[1]?"A":"P")+"M : "+a);25<u.log.length&&u.log.shift();a=("ktb: "+a).replace(/\+/g,"\uff0b").replace(/&/g,encodeURIComponent("&"))}u.hasOwnProperty("log")||e.log(a.replace(/(\r\n|\n|\r|\\n)/gm,
" ").trim())},s:function(a){var t=Array.prototype.slice.call(arguments),f,k=0,m;if(Array.isArray&&Array.isArray(a)||a instanceof Array)a=a.join("\n"+d);a&&"string"===typeof a&&("Enable"===c.multi_line_safe&&(f=a.split(/ *\n */),k=f.length,a=f[0]),t[0]=(d+a.replace(/\+/g,"\uff0b")).replace(/&/g,encodeURIComponent("&")));e.chatNotice.apply(e,t);for(m=1;m<k;m++)t[0]=f[m].replace(/\+/g,"\uff0b").replace(/&/g,encodeURIComponent("&")),e.chatNotice.apply(e,t)},a:function(e,c){var f=Array.prototype.slice.call(arguments);
if(Array.isArray&&Array.isArray(e)||e instanceof Array)e=e.join("\n"+d+"");c&&"string"===typeof c&&c.length&&(f[0]=""+e,void 0!==f[2]&&void 0===f[3]&&(f[3]=f[2],f[2]="#a2a9ad"),a.s.apply(r,f))},w:function(a,d){e.setTimeout(a,1E3>d?1E3:d)},I:function(d){var m=c[d]||"",f=/[\u0081-\u00ff]{1,}\u0080[\u0081-\u00ff]{1,}/g;null!==m.match(f)&&(a.a(["Message from the author:\n"+(a.i?"":"\u00a0\u00a0Thanks for using my "+a.g()+" :)\n")+"\u00a0\u00a0It "+(k?"also ":"")+'looks like you used a special character in your "'+
d.replace(/_/g," ")+'" setting\n\u00a0\u00a0that the '+a.g()+" system may have corrupted :(\n\u00a0\u00a0Please see the "+a.g()+" Description for more details and help.","End of Message"],e.room_slug,"#fdf2f9"),m=m.replace(f,""),k=a.i=!0);return m},D:function(a){d=(a||d).replace(/\s*:\s*$/,"");d.length&&(d+=": ")},F:function(){return this[Math.floor(Math.random()*this.length)]}},m=e.onMessage;e.onMessage=function(d){if("function"!==typeof d)throw new TypeError(d+" is not a function");m(function(c){var f=
c.m,m=c.user,k="rubzombie"===m,p=m===e.room_slug,r=RegExp("\\/(ktb|#[0-3])?((?:log))(?:\\s+([^\\/]+))?","ig"),q,b;if(!c["X-Spam"]&&/^\s*\//.test(f))for(;null!==(q=r.exec(f));)if(b=(q[1]||"ktb").toLowerCase(),"ktb"===b||b===a.h)if(c["X-Cmd"]=!0,b=q[2].toLowerCase(),p||k)switch(b){case "log":(p||k)&&a.b.hasOwnProperty("log")&&a.a("Log:\n\u00a0\u00a0"+a.b.log.join("\n\u00a0\u00a0"),m,"#f37ef3")}else a.a("Sorry, /"+(q[1]||"")+q[2]+" is a broadcaster-only command.",m,"#fdf2f9");return d(c)});return d};
e.onMessage(function(a){return a});a.D(c.ktb_notice_label);return a}(cb),C=function(e){function r(b){b=/^\d+$/.exec(b.replace(/^\s+|\s+$/g,""));null!==b&&(b=Number(b[0]));return b}function c(b,a,f){return f.indexOf(b)===a}function d(b){var a=/\\u([0-9a-f]{4})/gi,f,d=[];for(b=b||"";null!==(f=a.exec(b));)d.push(f[1]);if(d.length)for(d=d.filter(c),a=0,f=d.length;a<f;a++)b=b.replace(new RegExp("\\\\u"+d[a],"gi"),String.fromCharCode(parseInt(d[a],16)));return b=b.replace(/(^|\s|\\n);-*\)/gm,"$1:wink ").replace(/(^|\s|\\n):-*\)/gm,
"$1:smile ").replace(/(^|\s|\\n):D/gm,"$1:woot ")}function k(){var b=[];"rubzombie"===e.room_slug&&b.push("version: 2015.09.17_1","*FULLY CUSTOMIZABLE* Keep track of your high tip king by adding a crown to the start of their messages ;)");b.push("Settings:\n\u00a0\u00a0king: "+(f.king.length?f.king:"(un-set)")+"\n\u00a0\u00a0king tip: "+f.king_tip+"\n\u00a0\u00a0crown: "+p.f);return b}function a(b){function d(b){b=b||"";var a=(new Date).valueOf()-(c.hasOwnProperty("last")?c.last:0);y.b("onPromote: elapsed: "+
a);b.length||1E3>6E4-a?c.rate&&(y.s("/tip "+(f.king_tip+1)+", or more to "+(f.king.length?'replace "'+f.king+'" as':"become")+" the new "+p.title+", and wear the "+p.name,b,"#d5ebf8"),b.length||(c.count=1,c.promoting=!1,c.last=(new Date).valueOf())):y.w(d,6E4-a)}function e(){c.last=(new Date).valueOf();c.count=0}var c=a;b=b||"";c.hasOwnProperty("mode")||(c.mode="chat");c.hasOwnProperty("rate")||(c.rate=25);c.hasOwnProperty("last")||(c.last=0);c.hasOwnProperty("promoting")||(c.promoting=!1);c.hasOwnProperty("reset")||
(c.reset=e);!c.hasOwnProperty("count")||b.length?d(b):(c.count++,c.count>c.rate&&!c.promoting&&(c.promoting=!0,d()))}function m(){"time"===a.mode&&a();var b=6E4-((new Date).valueOf()-(a.hasOwnProperty("last")?a.last:0))%6E4;y.w(m,1E3>b?6E4:b)}function l(b,a,c){function f(b){for(var a=/(?:^|\s):([\w\-][\w\-]+)(?=\s|$)/g,c,d=[];null!==(c=a.exec(b));)d.push(c[1]);return d.join(" ")}function e(b){return b.replace(/(:ktb_crown|:ttlb_(?:bronze|gold|silver))/g,"(\\\\:ktb_crown|\\\\:ttlb_(?:bronze|gold|silver))").replace(/\?\?/g,
"([0-9a-z_]{3,})").replace(/\$\$/g,"([0-9OlI,\\\\.]+)").replace(/\:\:/g,"\\\\:\\\\:+").replace(/\s/g,"\\\\s*")}this.f=d(b||"HTKing");e(this.f);this.tag=this.f+" :: $$ :: ";this.C=new RegExp(e(this.tag),"g");this.G=f(this.f);this.u=d(a||"Hail high tip :: $$ :: king ?? "+this.f);this.B=new RegExp(e(this.u),"g");this.H=f(this.u);this.title=d(c||"King of High Tips");this.name=/^\s*[^a-zA-Z0-9]/.test(this.f)?"high tip "+this.f:this.f+" crown!"}function u(){y.b("version: 2015.09.17_1");var b=(new Date).valueOf();
x.Text=new l;x.Glyph=new l("\u265a");x.Graphic=new l(":ktb_crown");x.Custom=new l(f.usr_crown,f.usr_hail,f.usr_title);f.king=(f.king||"").toLowerCase().trim();f.king_tip=parseInt(f.king_tip||0,10);p=x[f.crown||"Text"];"Custom"===f.crown&&y.D(f.ktb_notice_label||e.room_slug+"'s KTBot");y.a(k(),e.room_slug,"#f2f9fd");a.hasOwnProperty("last")&&a.hasOwnProperty("count")&&(delete a.last,delete a.count);a();m();u.chat_count=0;u.start_time=(new Date).valueOf();y.b("init: "+((new Date).valueOf()-b)+"ms")}
function t(b){function c(){if(t||D){var b=k();b.push("In-chat commands:\n\u00a0\u00a0/crown\n\u00a0\u00a0/hail - hail the current high tip king\n\u00a0\u00a0/?\n\u00a0\u00a0/help - show this message\nTo adjust settings, deactivate & re-launch "+y.g()+".");y.a(b,n,"#f2f9fd")}else a(n)}function d(a){a.length&&(b.hasOwnProperty("ngg_whitelisted")?"string"===typeof b.ngg_whitelisted?b.ngg_whitelisted+=" "+a:(y.b("onMessage:replacing un-recognised ngg_whitelisted property: "+b.ngg_whitelisted),b.ngg_whitelisted=
a):b.ngg_whitelisted=a)}if(b.hasOwnProperty("ktb_slot"))return y.b("onMessage:duplicate ktb in slot: "+b.ktb_slot),null===w&&(y.a("Please note, a copy of this "+y.g()+" is already running in slot: "+b.ktb_slot,e.room_slug,"#f37e7e","#f5f5f5"),w=b.ktb_slot),b;var m=b.m,h,n=b.user,D="rubzombie"===n,t=n===e.room_slug;h=RegExp("\\/(kingtipperbot|ktb|#[0-3])?(bip|chat|crown|hail|help|time|tips|\\?)\\s*(\\d+)?","ig");var l,v=!1,q,B,A=!1;if(!b["X-Spam"]&&"/"===m.trim()[0])for(;null!==(l=h.exec(m));)if(v=
!0,q=(l[1]||"ktb").toLowerCase(),"ktb"===q||"kingtipperbot"===q||q===y.h)switch(b["X-Cmd"]=!0,B=l[3]||"",q=l[2].toLowerCase(),q){case "bip":y.a("Sorry, /"+(l[1]||"")+l[2]+" is a broadcaster-only, author-only, pre-release-only command.",n,"#f37e7e","#f5f5f5");break;case "chat":case "time":case "tips":t&&(a.mode!==q&&(a.mode=q,y.a(q+" based promo repeats set.",n,"#f2f9fd")),null!==(l=r(B))&&(a.rate=60<l?60:l,a.reset()),0===a.rate?y.a("promos temporarily suspended.",n,"#f2f9fd"):y.a("promo repeat rate set to one promo every "+
a.rate+("chat"===a.mode?" message":"time"===a.mode?" minute":" tip")+(1===a.rate?"":"s")+".",n,"#f2f9fd"));break;case "crown":case "hail":t&&(A=!0);break;case "?":case "help":c()}A&&null!==f.king&&f.king.length&&(b.m=p.u.replace("$$",f.king_tip).replace("??",f.king),d(p.H),b.ktb_slot=y.h,b["X-Cmd"]=!1,a.reset());b["X-Spam"]||v||u.hasOwnProperty("chat_count")&&u.chat_count++;b["X-Spam"]||A||(null!==(h=m.match(p.C))?(y.a('Sorry, "'+h.join('", and "')+'" '+(1===h.length?"has":"have")+' been removed from your message "'+
m+'".',n,"#d5ebf8"),y.a((f.king!==n.toLowerCase()?"Non-":"")+'High Tip King "'+n+'" looks like they might have tried to spoof the "'+x.Text+'" label in a message. Type /help or /? if you have any doubt about who the real high tip king is or what the real high tip value is ;)',e.room_slug,"#f37e7e")):null!==(h=m.match(p.B))&&(y.a('Sorry, "'+h.join('", and "')+'" '+(1===h.length?"has":"have")+' been removed from your message "'+m+'".',n,"#d5ebf8"),y.a('"'+n+'" looks like they might have tried to spoof the /hail message. Type /help or /? if you have any doubt about who the real high tip king is or what the real high tip value is ;)',
e.room_slug,"#f37e7e")),b.m=m.replace(p.B,"").replace(p.C,""),n.toLowerCase()!==f.king||/^(\/|!)/.test(m.trim())||(b.m=p.tag.replace("$$",f.king_tip)+b.m,d(p.G),b.ktb_slot=y.h,a.reset()),"chat"===a.mode&&a());return b}var f=e.settings,w=null,x={},p=null;"[object Array]"!=={}.toString.call(e.settings_choices)&&(e.settings_choices=[]);e.settings_choices.push({label:"Reigning High Tip King (user name)",maxLength:30,minLength:3,name:"king",required:!1,type:"str"},{label:"Reigning High Tip (tokens)",minValue:1,
name:"king_tip",required:!1,type:"int"},{label:'Custom Crown (e.g. ":custom_crown", see Description for details)',minLength:1,name:"usr_crown",required:!1,type:"str"},{label:'Custom Title (e.g. "King of High Tips", see Description for details)',minLength:1,name:"usr_title",required:!1,type:"str"},{label:'Custom Hail (e.g. "Hail high tip :: $$ :: king ?? :custom_crown", see Description for details)',minLength:1,name:"usr_hail",required:!1,type:"str"});e.settings_choices.unshift(new (Function.prototype.bind.apply(g,
[null,'What type of "Crown" do you want for King High Tipper?',"crown",null].concat(["Text","Glyph","Graphic","Custom"]))));var v=e.onMessage;e.onMessage=function(b){if("function"!==typeof b)throw new TypeError(b+" is not a function");v(function(a){a=t(a);return b(a)});return b};e.onMessage(function(a){return a});var q=e.onTip;e.onTip=function(b){if("function"!==typeof b)throw new TypeError(b+" is not a function");q(function(c){var d=c.from_user.toLowerCase(),e=c.amount;f.king_tip<e&&(f.king_tip=
e,f.king!==d&&(f.king=d,y.s(d+" has been crowned the new "+p.title+".\u00a0\u00a0Long Live the King!","","#f2f9fd")));"tips"===a.mode&&a();b(c)});return b};e.onTip(function(){});return{A:u}}(cb);
(function(e){function r(a){function l(a){var c=[];d.block_spam="Yes"===d.block_spam?"No":"Yes";d.spam_blocker_ad="Yes"!==d.block_spam;c.push(b.toUpperCase()+" Spam Blocking "+("Yes"===d.block_spam?"enabled. ":"disabled."),"Type /"+a+" again to "+("Yes"===d.block_spam?"disable it.":"block "+(k.length?"similar messages":"common spam")+" from appearing in chat."));"Yes"!==d.block_spam&&k.length&&c.splice(1,0,"Recently Blocked Messages:\n\u00a0\u00a0"+k.slice(-3).join("\n\u00a0\u00a0"));y.a(c,e.room_slug,
"#f2f9fd");k.length&&(k=[])}function u(){var b=f.replace(/[\W_]/g,"").toLowerCase(),p=b.replace(/[aeiou]/g,""),h,n,l=!1;h=f;n=w;l=!1;n=n.replace(/_[0-9a-f]+/ig,"");t.hasOwnProperty("echo_user")&&t.hasOwnProperty("echo_text")&&(l=t.echo_text===h&&t.echo_user===n);t.echo_user=n;t.echo_text=h;!0===l&&y.b("SpamBlockerAd: echo match");h=0;for(n=c.j.length;!l&&h<n&&!(p.length<c.j[h].length);h++)!0===(l=-1!==p.indexOf(c.j[h]))&&y.b("SpamBlockerAd: simple match ("+h+"): "+c.j[h]);h=0;for(n=c.l.length;!l&&
h<n;h++)!0===(l=c.l[h].test(f))&&y.b("SpamBlockerAd: text match ("+h+"): "+c.l[h].source);h=0;for(n=c.v.length;!l&&h<n;h++)!0===(l=c.v[h].test(b))&&y.b("SpamBlockerAd: plain match ("+h+"): "+c.v[h].source);h=0;for(n=c.o.length;!l&&h<n;h++)!0===(l=(new RegExp("(?:^|\\s):"+c.o[h]+"(?=\\s|$)","")).test(f))&&y.b("SpamBlockerAd: blacklist emoticons match ("+h+"): "+c.o[h]);l&&("Yes"===d.block_spam?(a["X-Spam"]=!0,k.push(w+": "+f)):(y.a(["Message from the author:\n"+(y.i?"":"\u00a0\u00a0Thanks for using my "+
y.g()+" :)\n")+'\u00a0\u00a0By the way, user "'+w+'" has just spammed your chat!\n\u00a0\u00a0You might want to type /spam to enable this '+y.g()+'"s basic spam blocking feature, or launch my spam blocker, '+y.F.call(["No\u00a0Grey\u00a0Spammers","Spam\u00a0Block"])+", for more protection ;)","End of Message"],e.room_slug,"#fdf2f9"),d.spam_blocker_ad=!1,y.i=!0))}var t=r,f=a.m,w=a.user,x="rubzombie"===w,p=w===e.room_slug,v=a.is_mod,q=RegExp("\\/(ktb|#[0-3])?((?:help|spam|\\?))(?:\\s+([^\\/]+))?","ig"),
b,z;if(d.spam_blocker_ad||"Yes"===d.block_spam)if(p||v){if(/\/(sh|sphammer|#[0-3])?(english|enonly|sphammered)/i.test(f)||/\/(sh|sphammer)(help|spam|\?)/i.test(f))d.spam_blocker_ad=!1,d.block_spam="No",y.b("SpamBlockerAd: SpHammer detected");/\/(ngs|nogreyspammers)(help|spam|\?)/i.test(f)&&(d.spam_blocker_ad=!1,d.block_spam="No",y.b("SpamBlockerAd: No Grey Spammers detected"))}else/<<<( has been SPAM HAMMERED| spHammer hit#)/.test(f)&&"#595959"===a.background&&"#999999"===a.c&&(d.spam_blocker_ad=
!1,d.block_spam="No",y.b("SpamBlockerAd: SpHammer/No Grey Spammers detected"));if(!a["X-Spam"]&&/^\s*\//.test(f))for(;null!==(v=q.exec(f));)if(b=(v[1]||"ktb").toLowerCase(),"ktb"===b||b===y.h)if(a["X-Cmd"]=!0,z=v[2].toLowerCase(),p||x)switch(z){case "spam":l((v[1]||"").toLowerCase()+z);break;case "?":case "help":y.a("Anti-spam in-chat commands:\n\u00a0\u00a0/spam - toggle common spam blocking on and off (="+("Yes"===d.block_spam?"on":"off")+")",w,"#f2f9fd")}else y.a("Sorry, /"+(v[1]||"")+v[2]+" is a broadcaster-only command.",
w,"#fdf2f9");p||a["X-Spam"]||a["X-Cmd"]||(d.spam_blocker_ad||"Yes"===d.block_spam)&&u();return a}var c={l:[/[^\u0000-\u0080\u00ad\u2605\u2606\u2654\u2655\u265a\u265b]/],v:[],j:"dlnws mcmcm rtmnt chnskv cht4fr wgwgwg bst4cms httpggl lv4prty lvtrffn nd4strp prfllsn bnjknntt kkmlvlns nsxyjngs pssy4shw vcmsssns wlchstdt 100kstnls chnnmnwhr cmsssnscm grls4prty prmmchtcm rgclsngsn sndtdrtch tknsgnrtr tmrqrllh1 tpgmscrck glsmtrprtl mnhndynmmr schnmnprfl schtglbntr snddrtchlv knntjmlgckn lslsnndmldn stdchlngwlg strmngnkdcm wtchmcmgrls chbnnjngsgls dtschmtrprtl fndfrtknshck hrgldtschkrl pyplrwstrnnn schfdsmwgdch wsnddglnpmml wstrnnnrpypl jckjxshrngnds kstnlsndhnrsk llrdngsnchthr mncmstjtztchn wndmrmnfrrlds dknnmnglbwchsn mprdndstrngtrk n1gnhmpgstfrtg chtwththswsmgrl stdnglchnnmnwhr wnnjrktwthmfrfr fsllnghtpcsndvds dsthtdstwchmmrsnd hbknfnnzllnntrssn nrnchbzckmtdntpps schfcktrffnndcmsx fdrstdnglchnnmnwhr llnfssthnmprflvnmr nynwnnjrktwthmfrfr vrllmsndfstnrdtsch glbdgbtsgrnchtmhrdr snddwskstnlsndglrst wsnddnnnndglndtschn chtrbtknnmndchvrgssn ftzstmgglndbrchtshrt mchvrdrcmllswshrwllt nynhrdrmstfckldrmlfs mchnchtlngwrtnndkmmzmr wrbckhtknnmchdjmlbschn kstnlsdtngprtlndtschlnd ntrssntbrmchfndstdnmnmprfl wnnjschtnmnprflndkntktrtmchdrt hbthrgntlchdhlfschlgschffthrvlldtn thsmnstrlysnfbtchsllngthmtfhsgrlfrnd dspmmrsndnfchzdmmvnjdmmdwrdnsgbnntndnsnstnflltdchknrfsnbldsnngwrbngrn".split(" "),
o:"anarchy dance69 endlesspoop exbf extremevomit extremevomit2 extremevomitscat FISTING fuckass1 gape420 gay gay6 gaybj gayfuck2 gayfuck5 gaysuck2 goats3 gross kena kisshug55 kisshug56 kisshug57 powerbottom prolapse56 prolapse57 prolapse58 shit50 shit55 shithead takeit tubgirl3 vbutt wag".split(" ")},d=e.settings,k=[];d.spam_blocker_ad="Yes"!==d.block_spam;"[object Array]"!=={}.toString.call(e.settings_choices)&&(e.settings_choices=[]);e.settings_choices.push(new g("In addition, would you like common forms of chat Spam to be blocked?",
"block_spam",!1,"Yes","No","Yes"));var a=e.onMessage;e.onMessage=function(c){if("function"!==typeof c)throw new TypeError(c+" is not a function");a(function(a){a=r(a);return c(a)});return c};e.onMessage(function(a){return a})})(cb);
(function(e){"[object Array]"!=={}.toString.call(e.settings_choices)&&(e.settings_choices=[]);e.settings_choices.push(new g("(Multi-line Safe Mode)","multi_line_safe",!1,"Disabled","Enabled"));e.settings_choices.push({"default":"King Tipper Bot",label:"Custom Notice Label (leave blank for vanilla notices)",minLength:1,name:"ktb_notice_label",required:!1,type:"str"});var r=e.onMessage;e.onMessage=function(c){if("function"!==typeof c)throw new TypeError(c+" is not a function");r(function(d){d.hasOwnProperty("X-Cmd")&&
(d["X-Spam"]=d["X-Cmd"],delete d["X-Cmd"]);return c(d)});return c};e.onMessage(function(c){return c})})(cb);cb.onSave(function(){return JSON.stringify(cb.settings)});cb.onRestore(function(e){var r=cb.settings,c=JSON.parse(e),d=["slot","king","king_tip"];Object.keys(c).forEach(function(e){-1===d.indexOf(e)&&(r[e]=c[e])});parseInt(c.king_tip,10)>r.king_tip&&(r.king=c.king,r.king_tip=c.king_tip);C.A()});C.A();
